
version: '3'

tasks:
  test:
    dir: '{{.TASKFILE_DIR}}'
    sources:
      - src/**/*.py
      - tests/**/*.py
      - pyproject.toml
    cmds:
      - uv run --offline python -m pytest -xs

  build:
    dir: '{{.TASKFILE_DIR}}'
    sources:
      - src/**/*.py
      - pyproject.toml
    deps:
      - test
    cmds:
      - rm -rf dist
      - uv run --offline --with build python -m build