
version: '3'

includes:
  py: ./python_packages/Taskfile.yml

tasks:
  bumpver-patch:
    deps:
      - fmt
      - lint
      - test
    sources:
      - python_packages/**/*.py
      - python_packages/**/data/*.onnx
      - python_packages/**/pyproject.toml
      - pyproject.toml
    cmds:
      - uv run --offline bumpver update --no-fetch --patch {{ .CLI_ARGS }}

  bumpver-minor:
    deps:
      - bumpver-patch
    sources:
      - python_packages/**/*.py
      - python_packages/**/pyproject.toml
      - pyproject.toml
    cmds:
      - uv run bumpver update --minor {{ .CLI_ARGS }}

  build:
    deps:
      - bumpver-patch
    cmds:
      - task: py:build

  publish:
    deps:
      - build
    cmds:
      - task: py:publish

  fmt:
    cmds:
      - task: py:fmt

  lint:
    cmds:
      - task: py:lint

  test:
    cmds:
      - task: py:test
  
