
version: '3'

includes:
  py: ./python_packages/Taskfile.yml

tasks:
  bumpver-patch:
    deps:
      - fmt
      - lint
      - test
    sources:
      - python_packages/**/*.py
      - python_packages/**/data/*.onnx
      # - python_packages/**/pyproject.toml
      # - pyproject.toml
    cmds:
      - uv run --offline bumpver update --no-fetch --patch {{ .CLI_ARGS }}

  bumpver-minor:
    deps:
      - bumpver-patch
    sources:
      - python_packages/**/*.py
      # I cannot use the pyproject as a source bc...
      # since this command changes the pyproject.toml
      # It creates a "never up to date loop"
      # - python_packages/**/pyproject.toml
      # - pyproject.toml
    cmds:
      - uv run bumpver update --minor {{ .CLI_ARGS }}

  build:
    deps:
      - bumpver-patch
    cmds:
      - task: py:build

  publish:
    deps:
      - build
    cmds:
      - task: py:publish

  gh-release:
    desc: Create a new GitHub release with built wheels
    deps:
      - build
    cmds:
      - |
        VERSION=$(uv run bumpver show | grep "Current Version:" | cut -d ":" -f2 | tr -d ' ')
        if [ -z "$VERSION" ]; then
          echo "Failed to get version from bumpver"
          exit 1
        fi
        echo "Creating release for version: $VERSION"
        echo gh release create "v$VERSION" ./python/dist/*.whl --title "v$VERSION" --notes "Release $VERSION"
    silent: false

  fmt:
    cmds:
      - task: py:fmt

  lint:
    cmds:
      - task: py:lint

  test:
    cmds:
      - task: py:test
  
