
from elfragmentador_core.config import IntensityTensorConfig

def _test_arrs():
    out = {"ion_type": [
            "b",
            "b",
            "b",
            "b",
            "b",
            "b",
            "b",
            "b",
            "b",
            "b",
            "b",
            "y",
            "y",
            "y",
            "y",
            "y",
            "y",
            "y",
            "y",
            "y",
            "y",
            "y",
            "y",
            "y",
            "y",
            "y",
            "y",
        ],
        "no": [
            4,
            5,
            7,
            8,
            9,
            10,
            19,
            11,
            12,
            13,
            15,
            2,
            3,
            4,
            5,
            7,
            15,
            16,
            8,
            18,
            19,
            9,
            10,
            11,
            12,
            13,
            15,
        ],
        "charge": [
            1,
            1,
            1,
            1,
            1,
            1,
            2,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            2,
            2,
            1,
            2,
            2,
            1,
            1,
            1,
            1,
            1,
            1,
        ],
        "intensity": [
            0.07,
            0.04,
            0.19,
            0.19,
            0.05,
            0.05,
            0.05,
            0.06,
            0.09,
            0.22,
            0.07,
            0.17,
            0.57,
            0.27,
            0.29,
            1.0,
            0.27,
            0.43,
            0.31,
            0.29,
            0.05,
            0.17,
            0.24,
            0.25,
            0.48,
            0.44,
            0.07,
        ],}
    
    return out

def test_intensity_conv():
    config = IntensityTensorConfig(max_charge=2, max_ordinal=10)
