
version: '3'

tasks:
  test:
    dir: '{{.TASKFILE_DIR}}'
    sources:
      - src/**/*.py
      - src/**/*.onnx
      - src/**/*.onnx.data
      - tests/**/*.py
      - pyproject.toml
    cmds:
      - uv run python -m pytest -xs

  build:
    dir: '{{.TASKFILE_DIR}}'
    sources:
      - src/**/*.py
      - src/**/*.onnx
      - src/**/*.onnx.data
      - pyproject.toml
    deps:
      - test
    cmds:
      - rm -rf dist
      - uv run --with build python -m build

  get-model:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - aws s3 cp s3://terraform-workstations-bucket/jspaezp/weights/ef_0.21.2/version_0/model_5.onnx src/elfragmentadonnx/data/model.onnx
      - aws s3 cp s3://terraform-workstations-bucket/jspaezp/weights/ef_0.21.2/version_0/model_5.onnx.data src/elfragmentadonnx/data/model_5.onnx.data