
version: '3'

includes:
  onnx: ./elfragmentadonnx/Taskfile.yml
  train: ./elfragmentador_train/Taskfile.yml
  core: ./elfragmentador_core/Taskfile.yml

tasks:
  build:
    desc: "Build all the packages and store the wheels in the dist directory"
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - rm -rf dist
      - task: onnx:build
      - task: train:build
      - task: core:build
      - mkdir -p dist
      - cp */dist/*.whl dist/

  publish:
    dir: '{{.TASKFILE_DIR}}'
    desc: "Copy all the wheels to the S3 bucket"
    deps:
      - build
    cmds:
      - for x in dist/*.whl ; do aws s3 cp $x s3://terraform-workstations-bucket/jspaezp/wheels/ ; done
    
  train-publish:
    dir: '{{.TASKFILE_DIR}}'
    desc: "Build the train+core packages and Copy all the wheels to the S3 bucket"
    cmds:
      - rm -rf dist
      - task: train:build
      - task: core:build
      - mkdir -p dist
      - cp */dist/*.whl dist/
      - for x in dist/*.whl ; do aws s3 cp $x s3://terraform-workstations-bucket/jspaezp/wheels/ ; done

    
  fmt:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - uv run ruff format

  lint:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - uv run ruff check

  test:
    desc: "Run the tests for all the python packages"
    cmds:
      - task: onnx:test
      - task: train:test
      - task: core:test