version: '3'

tasks:
  check-train:
    dir: '{{.TASKFILE_DIR}}'
    env:
      PYTORCH_ENABLE_MPS_FALLBACK: 1
      RUST_BACKTRACE: 1
    cmds:
      - uv run python -m elfragmentarust_train.training --data_dir ../part_data/ 

  clean:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - rm -rf dist
      - rm -rf build
      - rm -rf elfragmentarust_train.egg-info
      - rm -rf lightning_logs
      - rm *.onnx *.onnx.data || echo "No onnx files to clean"
  
  test:
    dir: '{{.TASKFILE_DIR}}'
    deps:
      - clean
    sources:
      - src/**/*.py
      - tests/**/*.py
      - pyproject.toml
    cmds:
      - uv run --with pytest python -m pytest -xs

  build:
    dir: '{{.TASKFILE_DIR}}'
    deps:
      - test
    cmds:
      - task: clean
      - uv run --with build python -m build




